-- Initial PostgreSQL schema for x-market-analysis.
--
-- Run through the project migration command:
--   uv run xmarket migrate
--
-- Or manually while learning:
--   docker exec -i xmarket-db psql -U xmarket -d xmarket < migrations/001_initial_schema.sql

CREATE TABLE authors (
    id text PRIMARY KEY,
    handle text NOT NULL,
    followers bigint NOT NULL DEFAULT 0,
    verified boolean NOT NULL DEFAULT false,
    account_tier text
);

CREATE INDEX ix_authors_handle ON authors (handle);

CREATE TABLE posts (
    id text PRIMARY KEY,
    author_id text NOT NULL REFERENCES authors (id),
    text text NOT NULL,
    created_at timestamptz NOT NULL,
    like_count bigint NOT NULL DEFAULT 0,
    repost_count bigint NOT NULL DEFAULT 0,
    reply_count bigint NOT NULL DEFAULT 0,
    lang text,
    raw jsonb NOT NULL,
    fetched_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX ix_posts_author_id ON posts (author_id);
CREATE INDEX ix_posts_created_at ON posts (created_at);

CREATE TABLE post_tickers (
    post_id text NOT NULL REFERENCES posts (id),
    ticker text NOT NULL,
    match_method text NOT NULL,
    confidence double precision NOT NULL DEFAULT 1.0,
    PRIMARY KEY (post_id, ticker)
);

CREATE INDEX ix_post_tickers_ticker ON post_tickers (ticker);

CREATE TABLE sentiments (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    post_id text NOT NULL REFERENCES posts (id),
    ticker text NOT NULL,
    label text NOT NULL,
    score double precision NOT NULL,
    model text NOT NULL,
    prompt_version text NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT uq_sentiment_post_ticker_prompt UNIQUE (post_id, ticker, prompt_version)
);

CREATE INDEX ix_sentiments_post_id ON sentiments (post_id);
CREATE INDEX ix_sentiments_ticker ON sentiments (ticker);

CREATE TABLE prices (
    ticker text NOT NULL,
    date date NOT NULL,
    open numeric(18, 6) NOT NULL,
    high numeric(18, 6) NOT NULL,
    low numeric(18, 6) NOT NULL,
    close numeric(18, 6) NOT NULL,
    adj_close numeric(18, 6),
    volume bigint NOT NULL DEFAULT 0,
    PRIMARY KEY (ticker, date)
);

CREATE TABLE signals (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name text NOT NULL UNIQUE,
    description text,
    conditions jsonb NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE backtest_runs (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    signal_id integer NOT NULL REFERENCES signals (id),
    params jsonb NOT NULL,
    results jsonb NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX ix_backtest_runs_signal_id ON backtest_runs (signal_id);
